### ISSUE TITLE
New Node.js NAPI

### ISSUE THREAD

**Issue by RReverser** [neon-bindings/neon#202] opened 2017-04-05 10:00 UTC
Now that Node.js has brought [support for a native API](https://github.com/nodejs/node/pull/11975), ABI-compatible across future Node.js versions or even different Node.js engines, are there any plans to use it instead of direct V8 API for Neon's bindings?

It looks like it could benefit the project, although unclear if it covers all the functionality Neon requires yet.

**Comment by Qard** [comment] 2017-04-12 03:10
It should be noted that it's feature flagged for now, but I'd definitely say it's worth looking into since it'll be a stable target eventually and can be used in pure C, so neon could make better use of Rust FFI rather than having to maintain [neon.cc](https://github.com/neon-bindings/neon/blob/master/crates/neon-runtime/src/neon.cc). 😸

**Comment by Qard** [comment] 2017-05-31 15:09
Released, but behind a --napi-modules flag.

**Comment by RReverser** [comment] 2017-05-31 17:55
@Qard Doesn't prevent from playing it (with using cfg(feature) for conditional compilation on Neon side).

**Comment by Qard** [comment] 2017-05-31 19:39
Yep, just wanted to be clear it's still behind a flag, so not production-ready yet, and could change at any time.

**Comment by dherman** [comment] 2017-10-11 05:22
I agree this is something we should eventually support, and I'd welcome experimentation! We can't switch to it overnight, but if NAPI pans out I would absolutely support switching to it when the time is right.

**Comment by Qard** [comment] 2017-10-11 06:10
N-API is no longer flagged as of Node.js 8.6.0, by the way. 🎉 

https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#2017-09-26-version-860-current-jasnell

**Comment by dherman** [comment] 2017-10-11 18:43
@Qard Nice! It's still marked as experimental and I don't really know how much it's likely to change in practice. It looks like [8.x will become LTS in a few weeks](https://github.com/nodejs/Release#release-schedule1) if I'm reading the schedule right, so we could technically switch to that soon. But it's still pretty new so I think it doesn't hurt to give it some time.

Anyway, none of that precludes us experimenting with this! I don't think it's the best use of _my_ time right now, since we have bigger issues to fix (especially the safety holes, the high level macro syntax, and fleshing out the API) first. But **if anyone is interested in working on this I will be happy to discuss it with them and actively mentor them**.

**Comment by RReverser** [comment] 2017-10-11 19:02
I could try to start implementing this after the next week unless someone wants to do it earlier.

**Comment by RReverser** [comment] 2017-11-14 19:24
I would definitely not mark this as beginner friendly, looks like it won't be that easy to preserve API compatibility without hacks.

**Comment by muditsaurabh** [comment] 2018-03-02 14:19
@RReverser Any update on this issue.

**Comment by fluxxu** [comment] 2018-03-08 17:28
For reference:
https://github.com/atom/xray/tree/master/napi

**Comment by devsnek** [comment] 2018-03-14 21:29
napi is considered stable at this point: https://github.com/nodejs/node/commit/cd7d7b15c1eeccfe2facdf9a671034d93b6bf467

**Comment by RReverser** [comment] 2018-03-15 12:31
I did look at extending Neon back in the day, but it seemed relying on V8 implementation details too much to have both implementations for V8 and NAPI. Now that NAPI is stable, full rewrite to get away from V8 API should be likely easier.

**Comment by devsnek** [comment] 2019-03-05 03:36
any word on this?

**Comment by amilajack** [comment] 2019-03-05 03:42
There are plans for this but it will likely be a while support for it gets added. The main focus as of now is to improve the existing API and DX

**Comment by amilajack** [comment] 2020-07-24 16:53
Duplicate of https://github.com/neon-bindings/neon/issues/444

**Closed** 2021-09-15 16:18 UTC
Labels: beginner friendly
