### ISSUE TITLE
document incompatibility with python 3

### ISSUE THREAD

**Issue by dherman** [neon-bindings/neon#301] opened 2018-03-29 21:44 UTC
In #298, @jacobwgillespie discovered that homebrew has started installing Python 3 by default, which breaks node-gyp. We should call this out explicitly in the macOS installation docs.

**Comment by jeffvandyke** [comment] 2018-04-16 19:12
Arch linux-based distros do this as well, where `which python` is a symlink to python3

**Comment by maxdobeck** [comment] 2019-08-21 18:59
Maybe this is answered else where but what is the plan for 1/1/2020?

When python 2.7 is no longer maintained?

**Comment by amilajack** [comment] 2019-08-21 19:01
@kjvalencik  let's move this conversation to http://github.com/neon-bindings/website/issues

**Comment by kjvalencik** [comment] 2019-08-21 19:24
I think we should keep this open to help track the progress on `node-gyp`. For what it's worth, `node-gyp` is an incredibly vital part of the node ecosystem.

@maxdobeck My understanding is that python 3 support for `node-gyp` is being worked on. At this point, I think it may be prudent to wait and see.

**Comment by black-puppydog** [comment] 2020-11-05 23:13
I propose to close this issue because the [Getting Started Guide](https://neon-bindings.com/docs/getting-started/) states "Python 3 is **not** supported" for all platforms.

However, I would also like to know if this is still the case, and if so, whether it will remain the case, and if there are any issues filed for that.

**Comment by amilajack** [comment] 2020-11-05 23:19
Seems like node-gyp [now supports python 3](https://github.com/nodejs/node-gyp#on-unix)

**Comment by ScottAwesome** [comment] 2021-03-08 16:18
First, thank you for this project! it is a real boost to creating fast interop between JS and rust for developer tools.

As pointed, node-gyp does support Python 3 now. I am curious what the status is on this project regarding that? Would help simplify the usage of this library for me (and likely others)

Keep up the great work!

**Comment by kjvalencik** [comment] 2021-03-08 16:55
@ScottAwesome If node-gyp supports python3, so should neon. If for some reason it's not working, it could be that node-gyp version needs to be bumped, but I thought we did that.

In either case, we are finishing up the n-api backend which doesn't require node-gyp or python at all. It only requires node and cargo.

**Comment by ScottAwesome** [comment] 2021-03-10 22:52
> @ScottAwesome If node-gyp supports python3, so should neon. If for some reason it's not working, it could be that node-gyp version needs to be bumped, but I thought we did that.
> 
> In either case, we are finishing up the n-api backend which doesn't require node-gyp or python at all. It only requires node and cargo.

@kjvalencik if I opened a PR documenting this, would that be cool? or is there any other reason to hold off that I'm just not thinking of?

**Comment by kjvalencik** [comment] 2021-03-10 23:35
@ScottAwesome I think we can close this issue. I'm pretty sure that Neon has worked with Python 3 for awhile. I checked and confirmed that CI is running with Python 3.

**Closed by kjvalencik** 2021-03-10 23:35 UTC
Labels: docs
