### ISSUE TITLE
Calling async API from node worker threads results in errors

### ISSUE THREAD

**Issue by kdy1** [neon-bindings/neon#489] opened 2020-02-18 01:04 UTC
Related: https://github.com/swc-project/node-swc/issues/21

Error message:

FATAL ERROR: HandleScope::HandleScope Entering the V8 API without proper locking in place

**Comment by dherman** [comment] 2020-02-29 06:58
@kdy1 Thank you for the report! Would you be able to provide us with a small code example so we can reproduce what you're trying to make work? Thank you!

**Comment by kdy1** [comment] 2020-02-29 07:17
@dherman I've created a basic version of module which invokes native addon from worker thread.
See: https://github.com/kdy1/neon-worker-thread

**Comment by PSeitz** [comment] 2020-09-08 11:26
Worker support is documented here:
https://nodejs.org/api/addons.html#addons_worker_support

**Comment by Lyoko-Jeremie** [comment] 2021-01-17 14:01
@kdy1 seems like it not work now.

**Comment by kjvalencik** [comment] 2021-01-17 15:47
@Lyoko-Jeremie The N-API backend does not have this issue.

**Comment by Lyoko-Jeremie** [comment] 2021-01-18 09:05
@kjvalencik where/when can i have it ?

**Comment by kjvalencik** [comment] 2021-01-18 15:02
Enable it in your `Cargo.toml`. https://github.com/neon-bindings/neon/blob/main/test/napi/Cargo.toml#L21

Docs for `EventQueue`. https://docs.rs/neon/0.7.0-napi.3/neon/event/struct.EventQueue.html

**Comment by Lyoko-Jeremie** [comment] 2021-01-18 22:19
@kjvalencik 

same reasult in the [worker_thread](https://nodejs.org/api/worker_threads.html)

```
sleeping: ThreadId(4)
sleeping done
scheduled
FATAL ERROR: HandleScope::HandleScope Entering the V8 API without proper locking in place
FATAL ERROR: HandleScope::HandleScope Entering the V8 API without proper locking in place
FATAL ERROR: HandleScope::HandleScope Entering the V8 API without proper locking in place

```

i use the  config

```

[build-dependencies]
neon-build = "0.7"

[dependencies]
#neon = { version = "0.6.0", features = ["event-handler-api"] }
neon = { version = "0.7", default-features = false, features = ["default-panic-hook", "napi-6", "try-catch-api", "event-queue-api"] }
```

code

```rust

pub fn async_task(mut cx: FunctionContext) -> JsResult<JsUndefined> {
    let undefined = cx.undefined();

    let cb = cx.argument::<JsFunction>(0)?.root(&mut cx);
    let queue = cx.queue();

    std::thread::spawn(move || {

        println!("sleeping: {:?}", thread::current().id());
        thread::sleep(std::time::Duration::from_secs(5));
        println!("sleeping done");
        queue.send(move |mut cx| {
            let callback = cb.into_inner(&mut cx);
            let this = cx.undefined();
            let null = cx.null();

            println!("Inside schedule fn");

            let args: Vec<Handle<JsValue>>  = vec![
                cx.string("abc").upcast::<JsValue>(),
                cx.number(100).upcast()
            ];

            callback.call(&mut cx, this, args)?;

            Ok(())
        });
        println!("scheduled");
    });

    Ok(undefined)
}


register_module!(mut cx, {
    cx.export_function("async_task", async_task)?;
    Ok(())
});
```

test it use :

```js
// test.js
// https://github.com/neon-bindings/neon/issues/489
// https://github.com/kdy1/neon-worker-thread
const {
    Worker,
    isMainThread,
    parentPort,
    workerData
} = require("worker_threads");
const rxjs = require('rxjs');

if (isMainThread) {
    module.exports = function parseJSAsync(script) {
        const s=new rxjs.Subject();

        const worker = new Worker(__filename, {
            workerData: script
        });
        worker.on("message", s.next.bind(s));
        worker.on("error", s.error.bind(s));
        worker.on("exit", code => {
            if (code !== 0)
                s.error(new Error(`Worker stopped with exit code ${code}`));
            console.log(`Worker stopped with exit code ${code}`);
            s.complete();
        });
        return s;
    };
} else {
    const addon = require('../native');
    addon.async_task(function (err, v) {
        parentPort.postMessage("Error: ", err);
        parentPort.postMessage("Result: ", v);
    });
    setTimeout(() => {
        console.error('end')
    }, 1000 * 8)
}
```



```js
// run.js
const t = require('./test')

console.log(t);
t().subscribe(
    value => {
        console.log(value)
    },
    error => {
        console.error(error)
    },
    () => {
        console.log('completed')
    }
);

```

**Comment by kjvalencik** [comment] 2021-01-19 01:48
@Lyoko-Jeremie Can you try deleting `index.node` and verifying the N-API version is being tested instead of a previous build?

I copied this code into a project and made minimal changes:
* Added `rxjs` dependency
* Added `use` statements to `lib.rs` so that the module compiles
* Updated `const addon = require('../native');` to load the module from the correct location

I ran the test 1000x and it passed successfully each time without the error.

```
$ node -v
v14.15.4

$ cargo version
cargo 1.51.0-nightly (329895f5b 2021-01-06)

$ rustc --version
rustc 1.51.0-nightly (a62a76047 2021-01-13)
```

**Comment by Lyoko-Jeremie** [comment] 2021-01-19 03:14
```
node -v
v12.18.3


cargo version
cargo 1.49.0 (d00d64df9 2020-12-05)


rustc --version
rustc 1.49.0 (e1884a8e3 2020-12-29)

```

is it my node verion too low ?

i will try to upgrade it.

**Comment by Lyoko-Jeremie** [comment] 2021-01-19 04:42
@kjvalencik 

now i upgrade the nodejs

```

>node -v
v14.15.4

>cargo version
cargo 1.49.0 (d00d64df9 2020-12-05)

>rustc --version
rustc 1.49.0 (e1884a8e3 2020-12-29)

```

and a new problem happend

```
    Finished dev [unoptimized + debuginfo] target(s) in 35.35s
neon info generating native\index.node
neon ERR! ENOENT: no such file or directory, copyfile 'H:\Code\WebstormProjects\license-client\native\target\x86_64-pc-window
s-msvc\debug\license_client.dll' -> 'H:\Code\WebstormProjects\license-client\native\index.node'

Error: ENOENT: no such file or directory, copyfile 'H:\Code\WebstormProjects\license-client\native\target\x86_64-pc-windows-m
svc\debug\license_client.dll' -> 'H:\Code\WebstormProjects\license-client\native\index.node'

Process finished with exit code 1

```

i can see the `license_client.dll.exp` and `license_client.dll.lib` file are generated, but the `license_client.dll` not on it's place.

![2021-01-19 12_41_44-Window](https://user-images.githubusercontent.com/6566869/104988702-bb887600-5a53-11eb-974d-a17958051c9a.png)


---

if i switch back to v0.6.0 like follow , all build will work well.

```

[build-dependencies]
neon-build = "0.6.0"
#neon-build = "0.7"

[dependencies]
neon = { version = "0.6.0", features = ["event-handler-api"] }
#neon = { version = "0.7", default-features = false, features = ["default-panic-hook", "napi-6", "try-catch-api", "event-queue-api"] }

```

where am i wrong ?

**Comment by Lyoko-Jeremie** [comment] 2021-01-19 05:33
now i install nightly version, `license_client.dll` still not on it's place.

```
> cargo version
cargo 1.51.0-nightly (a73e5b7d5 2021-01-12)

> rustc --version
rustc 1.51.0-nightly (d98d2f57d 2021-01-18)
```

**Comment by Lyoko-Jeremie** [comment] 2021-01-19 05:50
oh, i use the https://github.com/neon-bindings/neon/issues/662 fixed the dll issue.

**Comment by Lyoko-Jeremie** [comment] 2021-01-19 05:56
now i get a `Error: internal error in Neon module: not implemented` error when use the [Async Task feature](https://neon-bindings.com/docs/async/)

is it not impl now ? or some feature flag not enable ?  or it will be delete in future ? @kjvalencik

**Comment by kjvalencik** [comment] 2021-01-19 11:48
Task will not be implemented in the N-API backend. It is completely removed in the next unreleased version.

Instead, use your own thread pool and callback in with `EventQueue`.

**Comment by Lyoko-Jeremie** [comment] 2021-01-19 19:48
@kjvalencik thank you ~

**Comment by kjvalencik** [comment] 2021-09-15 21:04
Closing since this does not apply to the Node-API backend. Also, I found out I was *wrong* on the usefulness of node worker pool tasks and they *will* be implemented. https://github.com/neon-bindings/rfcs/pull/35

**Closed by kjvalencik** 2021-09-15 21:04 UTC
