### ISSUE TITLE
Panic inside an EventHandler scheduler aborts

### ISSUE THREAD

**Issue by pimeys** [neon-bindings/neon#500] opened 2020-03-18 09:56 UTC
Here's an example codebase:

``` rust
use neon::prelude::*;

pub struct Abort;

declare_types! {
    pub class JsAbort for Abort {
        init(_) {
            Ok(Abort)
        }

        method abort(mut cx) {
            let this = cx.this();
            let func = cx.argument::<JsFunction>(0)?;
            let cb = EventHandler::new(&cx, this, func);
            let opt: Option<()> = None;

            cb.schedule(move |cx| {
                opt.unwrap(); // boom
                vec![cx.number(1.0)]
            });

            Ok(cx.undefined().upcast())
        }
    }
}

register_module!(mut cx, {
    cx.export_class::<JsAbort>("Abort")?;
    Ok(())
});
```

``` javascript
const { Abort } = require('../native');

const abort = new Abort();
abort.abort((res) => {
    console.log(res);
});
```

Executing this code will not panic, but gives a `SIGABORT` instead. If moving the panicking code out from the `schedule` function, we get a normal panic again.

Version: 0.4.0
OS: Arch Linux

**Comment by kjvalencik** [comment] 2020-03-18 17:10
This is a known issue and a weakness of the API. Additionally, there is no way to correctly handle the `Err` if you would like. This is the primary reason the API is marked unstable.

We will likely implement a low level `try_catch` API and a high level version of `EventHandler` that uses it under the hood.

**Comment by pimeys** [comment] 2020-03-18 17:12
Good to know. We will probably use it anyhow when the n-api support is there. Just need to be careful not to panic!

**Comment by kjvalencik** [comment] 2020-03-18 17:45
Unfortunately, that might not be possible. There are certain `neon` APIs (e.g., `Buffer`) that can fail.

**Comment by andrebsguedes** [comment] 2020-07-02 01:08
I am hitting this also. Is there any way to get the panic trace and message? Without proper info it's very hard to identify the root cause.

**Comment by kjvalencik** [comment] 2021-09-15 20:59
Closing since the Node-API backend no longer adds a global panic handler and `try_catch` can handle JS failures.

**Closed by kjvalencik** 2021-09-15 20:59 UTC
