### ISSUE TITLE
Avoid Recompiling Crates

### ISSUE THREAD

**Issue by nixpulvis** [neon-bindings/neon#270] opened 2017-11-07 19:53 UTC
When I run `neon build` it will always compiles every crate.

**Comment by nixpulvis** [comment] 2017-11-09 21:07
This may be a more general version of #242.

**Comment by dherman** [comment] 2017-11-12 04:51
@nixpulvis Awesome, I've been looking to reproduce! Can you provide me as much info as possible about your build environment?

- OS?
- Node version?
- Rust version?
- Electron vs normal Node?
- Contents of your `native/artifacts.json` file?
- Ideally the full contents of the projects, if you're willing/able to share the source

Thanks!

**Comment by nixpulvis** [comment] 2017-11-12 18:56
@dherman well this is embarrassing... I've updated a few system dependencies since I opened this issue, and now I can't reproduce it either!

FWIW I'm now running:

- `Linux x86_64 4.13.11-1-ARCH`
- `node v8.8.1`
- rustc 1.22.0-nightly (4c053db23 2017-10-22)
- I haven't played with Electron yet.

Sorry for not including this info when I opened the issue, because we might have stood a chance then. I really wish I had an OS that let me rewind :P

**Comment by dherman** [comment] 2017-11-17 20:58
@nixpulvis I'll go ahead and close this for now since we haven't been able to reproduce. But please do keep an eye on it and reopen if you see it happen again!

**Closed by dherman** 2017-11-17 20:58 UTC

**Comment by nixpulvis** [comment] 2017-11-20 15:42
@dherman I think the issue is with successful crates not being cached on a failing build. So until I get the whole thing to compile once I need to recompile every crate.
