### ISSUE TITLE
Documentation site has a lot of broken links

### ISSUE THREAD

**Issue by king-alpha** [neon-bindings/neon#413] opened 2019-06-11 15:44 UTC
an example is [https://neon-bindings.com/handles-and-memory/](url).

**Comment by kjvalencik** [comment] 2019-06-11 17:06
FYI, here is the website repo: https://github.com/neon-bindings/website

**Comment by king-alpha** [comment] 2019-06-11 17:20
Oh okay.. Thanks, so which site did I visit then ?

**Comment by kjvalencik** [comment] 2019-08-16 19:27
Duplicate of https://github.com/neon-bindings/website/issues/78

**Closed by kjvalencik** 2019-08-16 19:27 UTC
