### ISSUE TITLE
Build fail in MacOS M1 with "Failed to run "node-gyp build" for neon-sys!"

### ISSUE THREAD

**Issue by sheepmen** [neon-bindings/neon#768] opened 2021-07-23 12:30 UTC
package.json
```
"scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "build:neon": "electron-build-env neon build native-rust",
    "lint": "vue-cli-service lint",
    "electron:build": "vue-cli-service electron:build",
    "electron:serve": "vue-cli-service electron:serve",
    "postinstall": "electron-builder install-app-deps",
    "postuninstall": "electron-builder install-app-deps"
  },
"dependencies": {
    "core-js": "^3.6.5",
    "electron-build-env": "^0.2.0",
    "element-ui": "^2.15.3",
    "native-rust": "^0.3.0",
    "neon-cli": "^0.8.3",
    "vue": "^2.6.11"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "babel-eslint": "^10.1.0",
    "bindings": "^1.5.0",
    "electron": "^13.0.0",
    "electron-build-env": "^0.2",
    "electron-devtools-installer": "^3.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^6.2.2",
    "vue-cli-plugin-electron-builder": "~2.1.1",
    "vue-template-compiler": "^2.6.11"
  },
```

```shell
yarn build:neon
```

output
```
error: failed to run custom build command for `neon-sys v0.8.3`

Caused by:
  process didn't exit successfully: `/Users/sheep3/workplace/xcoinai/xcoinai-gui/node_modules/native-rust/native/target/debug/build/neon-sys-6793f7d04b7f5e5a/build-script-build` (exit code: 101)
  --- stdout
  Skipping node-gyp installation as part of npm install.

  --- stderr
  thread 'main' panicked at 'Failed to run "node-gyp build" for neon-sys!
   Out: 
  > build-debug
  > node-gyp build --verbose --debug

    c++ -o Debug/obj.target/neon/src/neon.o ../src/neon.cc '-DNODE_GYP_MODULE_NAME=neon' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DV8_COMPRESS_POINTERS' '-DV8_31BIT_SMIS_ON_64BIT_ARCH' '-DV8_REVERSE_JSARGS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' '-DDEBUG' '-D_DEBUG' '-DV8_ENABLE_CHECKS' -I/Users/sheep3/.electron-gyp/13.1.7/include/node -I/Users/sheep3/.electron-gyp/13.1.7/src -I/Users/sheep3/.electron-gyp/13.1.7/deps/openssl/config -I/Users/sheep3/.electron-gyp/13.1.7/deps/openssl/openssl/include -I/Users/sheep3/.electron-gyp/13.1.7/deps/uv/include -I/Users/sheep3/.electron-gyp/13.1.7/deps/zlib -I/Users/sheep3/.electron-gyp/13.1.7/deps/v8/include -I../node_modules/nan  -O0 -gdwarf-2 -mmacosx-version-min=10.13 -arch arm64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++1y -stdlib=libc++ -fno-rtti -fno-exceptions -fno-strict-aliasing -MMD -MF ./Debug/.deps/Debug/obj.target/neon/src/neon.o.d.raw   -c

   Err: gyp info it worked if it ends with ok
  gyp verb cli [
  gyp verb cli   '/Users/sheep3/.nvm/versions/node/v14.17.3/bin/node',
  gyp verb cli   '/Users/sheep3/workplace/xcoinai/xcoinai-gui/node_modules/native-rust/native/target/debug/build/neon-sys-1518707c3861e7d3/out/native/node_modules/.bin/node-gyp',
  gyp verb cli   'build',
  gyp verb cli   '--verbose',
  gyp verb cli   '--debug'
  gyp verb cli ]
  gyp info using node-gyp@7.1.2
  gyp info using node@14.17.3 | darwin | arm64
  gyp verb command build []
  gyp verb build type Debug
  gyp verb architecture arm64
  gyp verb node dev dir /Users/sheep3/.electron-gyp/13.1.7
  gyp verb `which` succeeded for `make` /usr/bin/make
  gyp info spawn make
  gyp info spawn args [ 'V=1', 'BUILDTYPE=Debug', '-C', 'build' ]
  In file included from ../src/neon.cc:2:
  In file included from ../node_modules/nan/nan.h:2884:
  ../node_modules/nan/nan_typedarray_contents.h:34:43: error: no member named 'GetContents' in 'v8::ArrayBuffer'
        data   = static_cast<char*>(buffer->GetContents().Data()) + byte_offset;
                                    ~~~~~~~~^
  In file included from ../src/neon.cc:8:
  ../src/neon_string.h:28:5: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
      maybe.ToLocal(&result);
      ^~~~~~~~~~~~~ ~~~~~~~
  ../src/neon.cc:223:20: error: no type named 'Contents' in 'v8::ArrayBuffer'
    v8::ArrayBuffer::Contents contents = buffer->GetContents();
    ~~~~~~~~~~~~~~~~~^
  ../src/neon.cc:223:48: error: no member named 'GetContents' in 'v8::ArrayBuffer'
    v8::ArrayBuffer::Contents contents = buffer->GetContents();
                                         ~~~~~~~~^
  1 warning and 3 errors generated.
  make: *** [Debug/obj.target/neon/src/neon.o] Error 1
  gyp ERR! build error 
  gyp ERR! stack Error: `make` failed with exit code: 2
  gyp ERR! stack     at ChildProcess.onExit (/Users/sheep3/workplace/xcoinai/xcoinai-gui/node_modules/native-rust/native/target/debug/build/neon-sys-1518707c3861e7d3/out/native/node_modules/node-gyp/lib/build.js:194:23)
  gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
  gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
  gyp ERR! System Darwin 20.4.0
  gyp ERR! command "/Users/sheep3/.nvm/versions/node/v14.17.3/bin/node" "/Users/sheep3/workplace/xcoinai/xcoinai-gui/node_modules/native-rust/native/target/debug/build/neon-sys-1518707c3861e7d3/out/native/node_modules/.bin/node-gyp" "build" "--verbose" "--debug"
  gyp ERR! cwd /Users/sheep3/workplace/xcoinai/xcoinai-gui/node_modules/native-rust/native/target/debug/build/neon-sys-1518707c3861e7d3/out/native
  gyp ERR! node -v v14.17.3
  gyp ERR! node-gyp -v v7.1.2
  gyp ERR! not ok 
  ', /Users/sheep3/.cargo/registry/src/github.com-1ecc6299db9ec823/neon-sys-0.8.3/build.rs:209:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
neon ERR! cargo build failed

Error: cargo build failed
    at Target.<anonymous> (/Users/sheep3/workplace/xcoinai/xcoinai-gui/node_modules/neon-cli/lib/target.js:98:27)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/sheep3/workplace/xcoinai/xcoinai-gui/node_modules/neon-cli/lib/target.js:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
electron-build-env error
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by kjvalencik** [comment] 2021-07-23 18:11
This is likely a duplicate of https://github.com/neon-bindings/neon/issues/760 where the issue is a changed API in V8.

**Closed** 2021-07-23 18:21 UTC
