### ISSUE TITLE
Constructing a class calls init twice

### ISSUE THREAD

**Issue by thebluefish** [neon-bindings/neon#709] opened 2021-04-05 01:37 UTC
In Rust: 
```rust
pub struct Foo();

declare_types! {
    pub class JsFoo for Foo {
        init(mut cx) {
            println!("new foo");
            Ok(Foo::new())
        }
    }
}
```
From js (specifically, a vuex store):
```js
new Foo()
```
Produces:
```
new foo
new foo
```
However it only outputs once when I take any argument in `init`.

**Comment by kjvalencik** [comment] 2021-04-05 13:14
@thebluefish I don't see how Neon could cause this. Can you try putting a log right before the `new Foo()` in your vuex store to ensure you aren't calling `new Foo()` twice?

I tested your example locally and confirmed that `new foo` was only logged once.

**Comment by thebluefish** [comment] 2021-04-06 01:13
Hi,

I believe this is related to Electron (`10.4.2` or `11.4.2`). I have tried using my neon lib two ways:

First, by including it directly in my node package (`native` is in my workspace), and requiring it remotely:
```js
import {remote} from 'electron'
const { Foo } = remote.require("../../native")
new Foo()
```
Secondly, I added a barebones `package.json` to `native`, added `"native": "file:native"` to my dependencies, and `yarn link`ed it to my package. Now I can use it directly from renderer:
```js
import { Foo } from 'native'
new Foo()
```
Which shows the same issue:
```
00:49:14 [DEBUG] (1) native::js::foo: new foo
00:49:14 [DEBUG] (1) native::js::foo: new foo
```

As a side note, I can get stdout logging from the former approach but not the latter - since it's in renderer process, any ideas for directing it to console?

**Comment by kjvalencik** [comment] 2021-04-06 12:34
@thebluefish Have you tried adding a `console.log` before or after `new Foo()` to confirm the calling code isn't being called twice?

**Comment by thebluefish** [comment] 2021-04-06 12:36
Hi,

Yes, I'm definitely only calling `new Foo()` once.

**Comment by kjvalencik** [comment] 2021-04-06 12:37
@thebluefish Are you able to create a repo that reproduces? I'm not able to reproduce. I tried with Electron 11.4.2 as well.

**Comment by thebluefish** [comment] 2021-04-06 12:38
If I do something like
```js
let foo = new Foo()
foo.bar()
```
Then it will print
```
new foo
new foo
bar
```

**Comment by thebluefish** [comment] 2021-04-06 13:43
I've boiled my project down to a (mostly) minimal example.

[exmvce.zip](https://github.com/neon-bindings/neon/files/6265066/exmvce.zip)

**Comment by kjvalencik** [comment] 2021-04-06 19:25
@thebluefish Thanks for providing the complete example. I inserted some console logging code:

```rust
            let global = cx.global();
            let console = global.get(&mut cx, "console")
                .unwrap()
                .downcast::<JsObject>()
                .unwrap();

            let log = console
                .get(&mut cx, "log")
                .unwrap()
                .downcast::<JsFunction>()
                .unwrap();

            let args = vec![cx.string("!!! Constructing Foo")];

            log.call(&mut cx, console, args).unwrap();
```

![image](https://user-images.githubusercontent.com/2471970/113766356-4e4bbf00-96eb-11eb-8d83-3add2b456f7f.png)

![image](https://user-images.githubusercontent.com/2471970/113766388-586dbd80-96eb-11eb-8199-546660e355fa.png)

The logging shows that the constructor is being called a 2nd time by the vue dev tools. I'm not _exactly_ clear why they do this (possibly to get the constructor name), but I can observe:

* It only happens once. I can insert lots of other `new Foo()` and there's only *one* extra
* It doesn't happen if I disable the vue dev tools

I am closing since the constructor is actually being called twice. Let me know if that doesn't seem to be the case.

**Closed by kjvalencik** 2021-04-06 19:25 UTC

**Comment by thebluefish** [comment] 2021-04-06 19:37
It sounds like I have much to learn with my debug tools. Thanks much for the help!
