### ISSUE TITLE
Unable to build on Node 15 / Windows 10

### ISSUE THREAD

**Issue by cowboyd** [neon-bindings/neon#624] opened 2020-11-06 17:42 UTC
neon-sys build just fine on node versions 12,14 in this project: https://github.com/thefrontside/ctrlc-windows

using the following toolchain:

```
C:\Users\cowboyd\ctrlc-windows>volta list
⚡️ Currently active tools:

    Node: v15.1.0 (current @ C:\Users\cowboyd\ctrlc-windows\package.json)
    Yarn: v1.22.10 (current @ C:\Users\cowboyd\ctrlc-windows\package.json)
    Tool binaries available:
        neon (current @ C:\Users\cowboyd\ctrlc-windows\package.json)
         (default)
```

Fails to build with the following error:

```
C:\Users\cowboyd\ctrlc-windows>neon build
neon info forcing rebuild for new build settings
neon info running cargo                                                                                                                                                          Compiling cfg-if v0.1.10                                                                                                                                                      Compiling semver-parser v0.7.0                                                                                                                                                Compiling cslice v0.2.0                                                                                                                                                       Compiling winapi v0.3.9
   Compiling semver v0.9.0
   Compiling neon-sys v0.5.0
error: failed to run custom build command for `neon-sys v0.5.0`

Caused by:
  process didn't exit successfully: `C:\Users\cowboyd\ctrlc-windows\native\target\debug\build\neon-sys-8d921df647b4c7a9\build-script-build` (exit code: 1)
  --- stdout

  > preinstall
  > echo 'Skipping node-gyp installation as part of npm install.'

  'Skipping node-gyp installation as part of npm install.'
  cargo:node_root_dir=C:\\Users\\cowboyd\\.node-gyp\\15.1.0
  cargo:node_lib_file=C:\\Users\\cowboyd\\.node-gyp\\15.1.0\\<(target_arch)\\node.lib
  cargo:node_arch=x64
  TARGET = Some("x86_64-pc-windows-msvc")
  HOST = Some("x86_64-pc-windows-msvc")
  AR_x86_64-pc-windows-msvc = None
  AR_x86_64_pc_windows_msvc = None
  HOST_AR = None
  AR = None
  running: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX64\\x64\\lib.exe" "-out:C:\\Users\\cowboyd\\ctrlc-windows\\native\\target\\debug\\build\\neon-sys-cd90f11d123d5ab0\\out\\libneon.a" "-nologo" "C:\\Users\\cowboyd\\ctrlc-windows\\native\\target\\debug\\build\\neon-sys-cd90f11d123d5ab0\\out\\native\\build\\Debug\\obj\\neon\\neon.obj"
  LINK : fatal error LNK1181: cannot open input file 'C:\Users\cowboyd\ctrlc-windows\native\target\debug\build\neon-sys-cd90f11d123d5ab0\out\native\build\Debug\obj\neon\neon.obj'
  exit code: 1181

  --- stderr


  error occurred: Command "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX64\\x64\\lib.exe" "-out:C:\\Users\\cowboyd\\ctrlc-windows\\native\\target\\debug\\build\\neon-sys-cd90f11d123d5ab0\\out\\libneon.a" "-nologo" "C:\\Users\\cowboyd\\ctrlc-windows\\native\\target\\debug\\build\\neon-sys-cd90f11d123d5ab0\\out\\native\\build\\Debug\\obj\\neon\\neon.obj" with args "lib.exe" did not execute successfully (status code exit code: 1181).


warning: build failed, waiting for other jobs to finish...
error: build failed
neon ERR! cargo build failed

Error: cargo build failed
    at Target.<anonymous> (C:\Users\cowboyd\ctrlc-windows\node_modules\neon-cli\lib\target.js:98:27)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\cowboyd\ctrlc-windows\node_modules\neon-cli\lib\target.js:24:58)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
```

**Comment by kjvalencik** [comment] 2020-11-06 20:12
Duplicate of https://github.com/neon-bindings/neon/issues/621#issuecomment-723085960
Work in progress PR: https://github.com/neon-bindings/neon/pull/623

**Closed by kjvalencik** 2020-11-06 20:12 UTC
