### ISSUE TITLE
No output from failures during `cargo test`

### ISSUE THREAD

**Issue by thegreatape** [neon-bindings/neon#487] opened 2020-02-11 13:03 UTC
Hello! I'm seeing something odd in the crate I'm developing using Neon. When I run the tests I've written with `cargo test`, they run, but the detailed output from failures seems to be getting dropped. I put together a minimal example repo here: https://github.com/thegreatape/neon-test-output-example

When I run `cargo test` from the `native` directory of that crate, I get:

```
$ cargo test
   Compiling neon-test-output-example v0.1.0 (/Users/thomas/Code/neon-test-output-example/native)
warning: unused `#[macro_use]` import
 --> src/lib.rs:1:1
  |
1 | #[macro_use]
  | ^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

    Finished test [unoptimized + debuginfo] target(s) in 0.74s
     Running target/debug/deps/neon_test_output_example-ed285252001e5fe7

running 1 test
test tests::test_failure ... FAILED

failures:

failures:
    tests::test_failure

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--lib'
```

Whereas what I expect (from the same test, dropped into a new crate generated by `cargo new --lib`) looks like:
```
$ cargo test
   Compiling vanilla-rust-failure v0.1.0 (/Users/thomas/Code/vanilla-rust-failure)
    Finished test [unoptimized + debuginfo] target(s) in 0.51s
     Running target/debug/deps/vanilla_rust_failure-da2bbe4a51fd38a3

running 1 test
test tests::test_failure ... FAILED

failures:

---- tests::test_failure stdout ----
thread 'tests::test_failure' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `2`', src/lib.rs:5:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.


failures:
    tests::test_failure

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--lib'
```

This sounds a lot like the rust issue described here: https://github.com/rust-lang/rust/issues/51162 but since it works for newly-generated crates without neon, I'm guessing there's something about how Neon itself is setting things up? I'm new to Rust, so haven't yet been able to dig in farther. 

This is on Rust 1.41.0 (`rustc 1.41.0 (5e1a79984 2020-01-27)`), Mac OS Catalina 10.15.2. Let me know if there's other info I can provide!

**Comment by kjvalencik** [comment] 2020-02-13 00:13
It's may be caused by the panic suppression. This can be disabled with the `default-panic-hook` feature. Please note, that as of writing, this feature is not in the published version of neon on crates.io.

```sh
cargo test --features default-panic-hook
```

What's interesting is that the code that suppresses rust panics should only be executed in the context of node.

**Comment by thegreatape** [comment] 2020-02-14 01:22
@kjvalencik Yep, looks like that's what going on here! I pulled in master and enabled the default-panic-hook feature like so: https://github.com/thegreatape/neon-test-output-example/commit/1c42a37baa1ac342b5134f361d091f777d801773

And now the output looks like I'd expect:

```
running 1 test
test tests::test_failure ... FAILED

failures:

---- tests::test_failure stdout ----
thread 'tests::test_failure' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`', src/lib.rs:16:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.


failures:
    tests::test_failure

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by amilajack** [comment] 2020-02-28 19:32
@kjvalencik for the time being should we add this flag to the `Cargo.toml.hbs` as a temporary workaround?

**Comment by kjvalencik** [comment] 2021-09-15 21:02
Closing since the panic hook is no longer applied by default.

**Closed by kjvalencik** 2021-09-15 21:02 UTC
