### ISSUE TITLE
How to parse an array of (structed) JS objects into Vec of rust struct without JSON?

### ISSUE THREAD

**Issue by thanathip-wisesight** [neon-bindings/neon#524] opened 2020-06-10 14:26 UTC
Is there any way to pass an array of object into a vector of  rust struct without using serde? 

I tried work around like this
```javascript

let object = {
a:1,
b:"string",
c:1.00
}
let arrayOfObject =  [object,object,object]
let arrayOfa = [1,1,1]
let arrayOfb = ["string","string","string"]
let arrayOfc=[1.00,1.00,1.00]

some_neon_lib(arrayOfa,arrayOfb,arrayOfc);
```

and in rust

```rust
struct SampleStruct {
a:usize;
b:String;
c:f32;
}
fn create_sample_struct(
a:usize,
b:String,
c:f32
) -> SampleStruct{
a,b,c
}
---------------------------------- neon native/lib.rs

let arrayOfa= cx.argument::<JsArray>(0)?;
let arrayOfb= cx.argument::<JsArray>(1)?;
let arrayOfc= cx.argument::<JsArray>(2)?;
let vec_of_a :Vec<Handle<JsValue>> =arrayOfa.to_vec(&mut cx)?;
//... so on for b and c
let sampleVec: Vec<SampleStruct> = vec![]
for index in 0 .. length-1 {
let a = vec_of_a [index].downcast::<JsNumber>().unwrap().value() as usize;
/ ... so on for b and c
let sample_post = create_sample_struct (
a,b,c
)
sampleVec.push(sample_post)

}
#process something with sample vec

```
The overhead of conversion manually is huge, and using JSON is much worse.

I can't find document about how to deal with this situation anywhere. Any suggestion? Thanks

**Comment by samizdatco** [comment] 2020-08-01 03:17
> There's `neon-serde` which can be helpful here. However, FYI, this will _not_ perform well because it requires crossing the JS/native boundary repeatedly.

Does that mean that `neon-serde` will be less efficient _in general_ than code like that in the example above? Or is it something about this specific case?

**Comment by kjvalencik** [comment] 2020-08-01 16:02
`neon-serde` will generate very similar to what you would write by hand. This won't perform well in general.

**Comment by samizdatco** [comment] 2020-08-01 20:17
I see, so the issue is just that passing Array or Object arguments from js and unpacking them on the rust side has more overhead than passing, say, Numbers and Strings as function arguments? Or am I misunderstanding?

**Comment by kjvalencik** [comment] 2020-08-01 20:20
Passing an array isn't more expensive, but passing an array and *reading* N elements from it is N times more expensive. The cost is linear with the number of keys _read_.

**Comment by jonahpelfrey** [comment] 2020-12-14 18:08
I am running into similar issues with passing an array of objects into a neon-rust module. The performance of neon_serde::from_value is too costly for our use case. Curious if you have a suggestion on how to get around this?

**Comment by kjvalencik** [comment] 2020-12-14 18:19
@jonahpelfrey There isn't a great way around this because each JavaScript element comes at a cost. Converting nested objects multiplies the issue.

The best recommendation I have is to try to restructure the data so that it doesn't require the complexity.

C an you use a typed `ArrayBuffer` to represent the data? For example, if you have `{ a: number, b: number, c: number }[]` where each `number` is a 32-bit integer, this will perform much better stored in a columnar format.

```
{ a: Int32Array, b: Int32Array, Int32Array }
```

In a columnar format, this only requires reading `4` javascript values instead of `3 * (n + 1)` values.

If the data is initially serialized (e.g., JSON string), it can perform better to defer the serialization to Rust. Now the complex data structure only crosses the boundary as a single JS element.

There are some other tricks, but most tips are dependent on the use case. Unfortunately there isn't a great way to make complex objects fast, only ways to avoid complex objects.

**Comment by jonahpelfrey** [comment] 2020-12-14 19:57
We have the flexibility to use either an `ArrayBuffer` or a JSON string. In both cases, I'm struggling to find examples of how to interact with that input from the rust side using neon. 

#### For an ArrayBuffer, would the handle wrap a JsBuffer?
`let js_arr_handle: Handle<JsBuffer> = cx.argument(0)?;`

#### For serialized JSON, would the handle wrap a JsString?
`let js_json_handle: Handle<JsString> = cx.argument(0)?;`

In terms of interacting with this data from rust, I would expect that if I use a columnar format, my rust struct would also use that format, instead of a vector of structs. Something like:

```rust
#[derive(Deserialize)]
struct InputData {
  a: Vec<i32>,
  b: Vec<i32>,
  c: Vec<i32>
}
```

Would the conversion still look like this?
`let obj: InputData = neon_serde::from_value(&mut cx, js_handle)?;`

Any feedback would be appreciated. I'm new to rust and neon and need all the help I can get.

**Comment by kjvalencik** [comment] 2020-12-14 22:24
@jonahpelfrey Yes, you are correct for `ArrayBuffer` and `JSON`. In both of those cases, `neon_serde` wouldn't be used, but instead `serde_json`.

I'm not super familiar with `neon_serde`, so I don't know off-hand if it supports `Buffer` types. It might need to be manually deserialized.

**Comment by kjvalencik** [comment] 2022-04-13 19:42
Closing since this question has a few answers in it.

**Closed by kjvalencik** 2022-04-13 19:42 UTC
