### ISSUE TITLE
Asciinema demo on neon-bindings.com has been archived

### ISSUE THREAD

**Issue by jeremy-w** [neon-bindings/neon#408] opened 2019-05-08 15:19 UTC
The page https://neon-bindings.com/ shows in the "A Demo" section:

![Screen Shot 2019-05-08 at 11 17 18](https://user-images.githubusercontent.com/29010/57386803-206a4280-7183-11e9-9308-67094fad9fb7.png)

Clicking opens: https://asciinema.org/a/ZXrZmY5ofORmdlKKrm8ev0QC7

Which says:

> ## This recording has been archived
>
> All unclaimed recordings (the ones not linked to any user account) are automatically archived 7 days after upload.

**Comment by kjvalencik** [comment] 2019-08-16 19:30
Duplicate of https://github.com/neon-bindings/website/issues/84

**Closed by kjvalencik** 2019-08-16 19:30 UTC
